apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: zk

namespace: kafka

resources:
- namespace.yaml
- statefulset.yaml
- service-client.yaml
- service-headless.yaml

configMapGenerator:
  - name: zk-env
    literals:
      #- ZOOKEEPER_SERVERS="zk-0.zk-headless.kafka.svc.cluster.local:2888:3888;zk-1.zk-headless.kafka.svc.cluster.local:2888:3888;zk-2.zk-headless.kafka.svc.cluster.local:2888:3888"
      #- ZOOKEEPER_SERVERS="zk-0.zk-headless.kafka.svc.cluster.local:2888:3888"
      - ZOO_STANDALONE_ENABLED=false
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_SERVERS=3
