apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: zk

namespace: kafka

resources:
- statefulset.yaml
- service-client.yaml
- service-headless.yaml

configMapGenerator:
  - name: zk-env
    literals:
      - ZOOKEEPER_SERVERS=3
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_SERVER_PORT=2888
      - ZOOKEEPER_LEADER_ELECTION_PORT=3888
      - ZOOKEEPER_DATA_DIR=/home/user/data
      - ZOOKEEPER_LOG_DATA_DIR=/home/user/logs
      - ZOOKEEPER_CLUSTER_DOMAIN="cluster.local"
      - ZOOKEEPER_NAMESPACE="kafka"
      - ZOOKEEPER_SUBDOMAIN="zk-headless"
