apiVersion: v1
kind: Service
metadata:
  name: zk-headless
  labels:
    app: zk
spec:
  ports:
  - name: server
    port: 2888
  - name: leader-election
    port: 3888
  clusterIP: None
  selector:
    app: zk