apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: zk

spec:
  serviceName: zk-headless
  selector:
    matchLabels:
      app: zk
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zk
    spec:
      hostname: $(POD_NAME)
      subdomain: "zk-headless"
      containers:
      - name: zk 
        imagePullPolicy: "Never"       
        image: "localhost/zookeeper:latest"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        ports:
        - name: client
          containerPort: 2181
          protocol: TCP
        - name: server
          containerPort: 2888
          protocol: TCP
        - name: leader-election
          containerPort: 3888
          protocol: TCP
        - name: jmx
          containerPort: 9556
          protocol: TCP
        volumeMounts:        
        - name: zk-data-pvc
          mountPath: "/home/user/data"
          subPath: $(POD_NAME)
        - name: zk-logs-pvc
          mountPath: "/home/user/logs"
          subPath: $(POD_NAME)
        envFrom:
        - configMapRef:
            name: zk-env
        env:
          - name: ZK_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      # DOESN'T WORK IN A SINGLE NODE CLUSTER, E.G. IN MINIKUBE WITH DEFAULTS
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchExpressions:
      #             - key: "app"
      #               operator: In
      #               values:
      #               - zk
      #         topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
    - metadata:
        name: zk-data-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: zk-logs-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi