apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: zk

spec:
  serviceName: zk
  selector:
    matchLabels:
      app: zk
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zk
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - zk
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: zk        
        image: "confluentinc/cp-zookeeper:7.0.0"
        command: ["/bin/bash", "-c", "export ZOOKEEPER_SERVER_ID=$((${HOSTNAME: -1} +1)) && /etc/confluent/docker/run"]
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        volumeMounts:        
        - name: zk-pvc
          mountPath: "/data"
          # subPath: $(POD_NAME)
        envFrom:
        - configMapRef:
            name: zk-env
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
  volumeClaimTemplates:
    - metadata:
        name: zk-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi