apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zk-2
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /dev/projects/kafka-kube/zk-data2