apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: kafka

resources:
- statefulset.yaml
- service-client.yaml
- service-headless.yaml

configMapGenerator:
  - name: kafka-env
    literals:
      - KAFKA_PORT=9092
      - KAFKA_LOG_DIRS=/home/user/data
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_ZOOKEEPER_CONNECT=zk-client.kafka.svc.cluster.local:2181
      - KAFKA_MIN_IN_SYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_SUBDOMAIN=kafka-client
      - KAFKA_NAMESPACE=kafka
      - KAFKA_CLUSTER_DOMAIN=cluster.local
      - KAFKA_HEAP_OPTS="-Xmx512M -Xms512M"
      - KAFKA_OPTS="-Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9010 -javaagent:/jmx_agent.jar=9556:/home/user/prometheus.conf"