apiVersion: v1
kind: Service

metadata:
  name: kafka-client
  labels:
    app: kafka

spec:
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
    - name: jmx
      port: 9556
      targetPort: jmx